docsets:
  - name: dask
    repo: https://github.com/dask/dask.git
    doc_dir: docs
    html_pages: build/html
  - name: distributed
    repo: https://github.com/dask/distributed.git
    doc_dir: docs
    html_pages: build/html
  - name: zarr
    repo: https://github.com/zarr-developers/zarr-python.git
    doc_dir: docs
    html_pages: _build/html
