docsets:
  - name: dask
    repo: dask/dask
    doc_dir: docs
    html_pages: build/html
  - name: distributed
    repo: dask/distributed
    doc_dir: docs
    html_pages: build/html
  - name: zarr
    repo: zarr-developers/zarr-python
    doc_dir: docs
    html_pages: _build/html
