docsets:
  - name: dask
    repo: dask/dask
    doc_dir: docs
    html_pages: build/html
  - name: distributed
    repo: dask/distributed
    doc_dir: docs
    html_pages: build/html
  - name: dask-jobqueue
    repo: dask/dask-jobqueue
    doc_dir: docs
    html_pages: _build/html
  - name: zarr
    repo: zarr-developers/zarr-python
    doc_dir: docs
    html_pages: _build/html
  - name: numcodecs
    repo: zarr-developers/numcodecs
    doc_dir: docs
    html_pages: _build/html
  - name: xarray
    repo: pydata/xarray
    doc_dir: doc
    html_pages: _build/html
  - name: climpred
    repo: bradyrx/climpred
    doc_dir: docs
    html_pages: build/html
  - name: intake
    repo: intake/intake
    doc_dir: docs
    html_pages: build/html
  - name: fsspec
    repo: intake/filesystem_spec
    doc_dir: docs
    html_pages: build/html
  - name: xgcm
    repo: xgcm/xgcm
    doc_dir: doc
    html_pages: _build/html
  - name: jupyterhub
    repo: jupyterhub/jupyterhub
    doc_dir: docs
    html_pages: build/html
  - name: binder
    repo: jupyterhub/binder
    doc_dir: doc
    html_pages: _build/html
  - name: binderhub
    repo: jupyterhub/binderhub
    doc_dir: doc
    html_pages: _build/html
  - name: numba
    repo: numba/numba
    doc_dir: docs
    html_pages: _build/html
  - name: xtensor
    repo: xtensor-stack/xtensor
    doc_dir: docs
    html_pages: build/html
  - name: proplot
    repo: lukelbd/proplot
    doc_dir: docs
    html_pages: _build/html
  - name: trio
    repo: python-trio/trio
    doc_dir: docs
    html_pages: build/html
  - name: sparse
    repo: pydata/sparse
    doc_dir: docs
    html_pages: _build/html
    script: sphinx-build -W -b html . _build/html
  - name: arviz
    repo: arviz-devs/arviz
    doc_dir: doc
    html_pages: _build/html
  - name: skorch
    repo: skorch-dev/skorch
    doc_dir: docs
    html_pages: _build/html
  - name: jax
    repo: google/jax
    doc_dir: docs
    html_pages: build/html
    script: sphinx-build -b html . build/html
  # - name: fastapi
  #   repo: tiangolo/fastapi
  #   doc_dir: .
  #   script: mkdocs build
  #   html_pages: ""
  #   use_dashing: true
  # - name: uvicorn
  #   repo: encode/uvicorn
  #   doc_dir: .
  #   script: mkdocs build
  #   html_pages: ""
  #   use_dashing: true
  # - name: starlette
  #   repo: encode/starlette
  #   doc_dir: .
  #   script: mkdocs build
  #   html_pages: ""
  #   use_dashing: true
