name: dash-docs
channels:
  - conda-forge
dependencies:
  - dask
  - dask-sphinx-theme
  - distributed
  - doc2dash
  - jupyterlab
  - make
  - nbsphinx
  - sphinx_rtd_theme
  - sphinx-issues
  - xarray
  - zarr
  - numpydoc
  - sphinx-click
  - pygithub
  - matplotlib
  - scipy
  - tqdm
  - cftime
  - docrep
  - dask-jobqueue
  - dask-kubernetes
  - jupyterhub
  - nodejs
  - alembic
  - sphinx-copybutton
  - paramiko
  - pip:
      - git+https://github.com/pandas-dev/pandas-sphinx-theme.git@master
      - sphinx-jsonschema
      - autodoc-traits
