name: dash-docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - alembic
  - bottleneck
  - breathe
  - cfgrib
  - cftime
  - dask
  - dask-jobqueue
  - dask-kubernetes
  - dask-sphinx-theme
  - distributed
  - doc2dash
  - docker-py
  - docrep
  - doxygen
  - escapism
  - fsspec
  - h5netcdf
  - intake
  - iris
  - jupyter_telemetry
  - jupyterhub
  - jupyterlab
  - make
  - nbsphinx
  - netcdf4
  - nodejs
  - numba
  - numpydoc
  - paramiko
  - pip
  - pygithub
  - rasterio
  - recommonmark
  - scipy
  - tqdm
  - trio
  - xtensor
  - zarr
  - matplotlib>3
  - cartopy
  - xarray
  - xgcm
  - climpred
  - seaborn
  - sphinx_bootstrap_theme
  - sphinx_rtd_theme
  - sphinx-automodapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-gallery
  - sphinx-issues
  - basemap
  - pip:
      - git+https://github.com/pandas-dev/pandas-sphinx-theme.git@master
      - git+https://github.com/pydata/xarray.git
      - git+https://github.com/numba/numba.git
      - sphinx-jsonschema
      - autodoc-traits
      - sphinxcontrib-napoleon
      - sphinxcontrib-trio
      - git+https://github.com/lukelbd/sphinx-automodapi@v0.6.proplot-mods
      - git+https://github.com/lukelbd/proplot.git
