name: dash-docs
channels:
  - conda-forge
dependencies:
  - bottleneck
  - cartopy
  - cfgrib
  - cftime
  - climpred
  - dask
  - dask-jobqueue
  - dask-kubernetes
  - dask-sphinx-theme
  - distributed
  - doc2dash
  - docker-py
  - docrep
  - escapism
  - fastapi
  - fsspec
  - h5netcdf
  - heapdict
  - intake
  - ipyleaflet
  - ipywidgets
  - iris
  - jax
  - jupyter-repo2docker
  - jupyter_telemetry
  - jupyterhub
  - jupyterlab
  - make
  - matplotlib>3
  - msgpack-python
  - nbsphinx
  - netcdf4
  - nodejs
  - numba
  - numpydoc
  - paramiko
  - pip
  - rasterio
  - recommonmark
  - scipy
  - seaborn
  - sparse
  - sphinx-automodapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-gallery
  - sphinx-issues
  - sphinx_bootstrap_theme
  - sphinx_rtd_theme
  - tqdm
  - trio
  - xarray
  - xgcm
  - xtensor
  - zarr
  - pip:
      - git+https://github.com/pandas-dev/pandas-sphinx-theme.git@master
      - git+https://github.com/pydata/xarray.git
      - git+https://github.com/numba/numba.git
      - git+https://github.com/lukelbd/sphinx-automodapi@v0.6.proplot-mods
      - autodoc-traits
      - markdown-include
      - mkautodoc
      - mkdocs
      - mkdocs-material
      - m2r
      - sphinx-jsonschema
      - sphinx-pangeo-theme
      - sphinxcontrib-napoleon
      - sphinxcontrib-trio
      - sphinx-fortran
      - sphinx_autodoc_typehints
      - jaxlib
      - jax
