name: dash-docs
channels:
  - conda-forge
dependencies:
  - alembic
  - arviz
  - basemap
  - bottleneck
  - bqplot
  - breathe
  - cartopy
  - cftime
  - dask
  - doc2dash
  - docker-py
  - docrep
  - doxygen
  - escapism
  - fastapi
  - fsspec
  - h5netcdf
  - ipywidgets
  - jupyterlab
  - make
  - matplotlib>3
  - msgpack-python
  - nbsphinx
  - netcdf4
  - nodejs
  - numba
  - numpydoc
  - paramiko
  - phantomjs
  - pip
  - pytorch
  - recommonmark
  - scipy
  - seaborn
  - selenium
  - skorch
  - sparse
  - sphinx-automodapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-gallery
  - sphinx-issues
  - sphinx_bootstrap_theme
  - sphinx_rtd_theme
  - tqdm
  - xarray
  - zfpy
  - heapdict
  - pip:
      - git+https://github.com/pandas-dev/pandas-sphinx-theme.git@master
      - git+https://github.com/lukelbd/sphinx-automodapi@v0.6.proplot-mods
      - git+https://github.com/lukelbd/proplot.git
      - autodoc-traits
      - markdown-include
      - mkautodoc
      - mkdocs
      - mkdocs-material
      - m2r
      - sphinx-jsonschema
      - sphinx-pangeo-theme
      - sphinxcontrib-napoleon
      - sphinxcontrib-trio
      - sphinx-fortran
