name: dash-docs
channels:
  - conda-forge
dependencies:
  - dask
  - distributed
  - dask-sphinx-theme
  - distributed
  - doc2dash
  - jupyterlab
  - nbsphinx
  - sphinx_rtd_theme
  - sphinx-issues
  - xarray
  - zarr
