name: dash-docs
channels:
  - conda-forge
dependencies:
  - alembic
  - bottleneck
  - breathe
  - cartopy
  - cfgrib
  - cftime
  - climpred
  - dask
  - dask-jobqueue
  - dask-kubernetes
  - dask-sphinx-theme
  - distributed
  - doc2dash
  - docker-py
  - docrep
  - escapism
  - fsspec
  - h5netcdf
  - hvplot
  - intake
  - iris
  - jupyter_telemetry
  - jupyterhub
  - jupyterlab
  - make
  - matplotlib
  - nbsphinx
  - netcdf4
  - nodejs
  - numba
  - numpydoc
  - paramiko
  - pip
  - pygithub
  - rasterio
  - recommonmark
  - scipy
  - seaborn
  - sphinx_bootstrap_theme
  - sphinx_rtd_theme
  - sphinx-click
  - sphinx-copybutton
  - sphinx-gallery
  - sphinx-issues
  - tqdm
  - xarray
  - xgcm
  - xtensor
  - zarr
  - doxygen
  - pip:
      - git+https://github.com/pandas-dev/pandas-sphinx-theme.git@master
      - sphinx-jsonschema
      - autodoc-traits
      - sphinxcontrib-napoleon
