name: dash-docs
channels:
  - conda-forge
dependencies:
  - alembic
  - basemap
  - bottleneck
  - bqplot
  - breathe
  - cartopy
  - cftime
  - doc2dash
  - docrep
  - doxygen
  - h5netcdf
  - jupyterlab
  - make
  - matplotlib>3
  - nbsphinx
  - netcdf4
  - nodejs
  - numpy
  - numpydoc
  - paramiko
  - pip
  - pytorch
  - recommonmark
  - scipy
  - seaborn
  - skorch
  - sparse
  - tqdm
  - xarray
  - zfpy
  - heapdict
  - pip:
      - pip
      - git+https://github.com/pandas-dev/pandas-sphinx-theme.git@master
      - git+https://github.com/lukelbd/sphinx-automodapi@v0.6.proplot-mods
      - git+https://github.com/lukelbd/proplot.git
      - autodoc-traits
      - m2r
      - markdown-include
      - mkautodoc
      - mkdocs
      - mkdocs-material
      - sphinx-automodapi
      - sphinx-click
      - sphinx-copybutton
      - sphinx-fortran
      - sphinx-gallery
      - sphinx-issues
      - sphinx-jsonschema
      - sphinx-pangeo-theme
      - sphinx_bootstrap_theme
      - sphinx_rtd_theme
      - sphinxcontrib-napoleon
      - sphinxcontrib-trio
