version: 2.1
# Tell CircleCI to use this workflow
jobs:
  build:
    docker:
      - image: ncarxdev/miniconda:3.8
    environment:
      SPHINXOPTS: "-j4"
      CONDA_PREFIX: "/opt/conda"
    steps:
      # Get our data and merge with upstream
      - checkout

      - restore_cache:
          key: deps-{{ checksum "environment.yaml" }}-{{ checksum "docsets-config.yaml" }}

      - run:
          name: Install Dependencies
          command: |
            conda env update -n base -f environment.yaml
            conda list

      - run:
          name: Build Dash Docsets
          command: |
            python build.py
          no_output_timeout: 30m

      - store_artifacts:
          path: docsets/

      - store_artifacts:
          path: feeds/

      - persist_to_workspace:
          root: .
          paths:
            - docsets/
            - feeds/
      - save_cache:
          key: deps-{{ checksum "environment.yaml" }}-{{ checksum "docsets-config.yaml" }}
          paths:
            - "/opt/conda/pkgs"

  deploy:
    working_directory: ~/project/dash-docsets
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
        # Add deployment key fingerprint for CircleCI to use for a push
      - add_ssh_keys:
          fingerprints:
            - "70:c1:49:27:4b:65:92:6f:c9:ed:07:43:db:a6:c0:6f"
      # Copying over built website to the live site
      - run:
          name: Copy over built site files
          command: |
            ls -ltrh /tmp/workspace/feeds
            ls -ltrh /tmp/workspace/docsets
            rm -rf docsets && cp -r /tmp/workspace/docsets ../docsets
            rm -rf feeds && cp -r /tmp/workspace/feeds ../feeds
      - run:
          name: Change to docsets branch and replace w/ new docsets
          command: |
            cp -r ./.circleci ./images README.md ../
            git checkout docsets
            rm -rf ./* .gitignore .isort.cfg .pre-commit-config.yaml ./.circleci
            cp -r ../.circleci ../images ../README.md ../docsets ../feeds ./
            ls -ltrh ./docsets
            ls -ltrh ./feeds
            git status
            git remote -v
      - run:
          name: Commit results and push to docsets
          command: |
            git config --global user.email "bot@andersonbanihirwe.dev"
            git config --global user.name "Samaritan"
            git add -A
            git commit -m "Automated deploy"
            git push -f origin docsets:docsets

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          filters:
            branches:
              ignore: docsets
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
              ignore:
                - docsets
  default:
    jobs:
      - build:
          filters:
            branches:
              ignore: docsets
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
              ignore:
                - docsets
