- name: xarray
  repo: pydata/xarray
  doc_dir: doc
  html_pages_dir: _build/html
- name: trio
  repo: python-trio/trio
  doc_dir: docs
  html_pages_dir: build/html
- name: dask
  repo: dask/dask
  doc_dir: docs
  html_pages_dir: build/html
- name: distributed
  repo: dask/distributed
  doc_dir: docs
  html_pages_dir: build/html
- name: dask-jobqueue
  repo: dask/dask-jobqueue
  doc_dir: docs
  html_pages_dir: _build/html
