- name: myst-parser
  repo: executablebooks/MyST-Parser
  doc_dir: docs
  html_pages_dir: _build/html
  doc_build_cmd: sphinx-build -T -E -b html ./ _build/html
  pixi_dependencies:
    sphinx: ">=8,<9"
    sphinx-book-theme: "*"
    sphinx-autodoc2: "*"
    sphinx-copybutton: "*"
    sphinx-design: "*"
    sphinx-tippy: "*"
    sphinx-togglebutton: "*"
    sphinxext-rediraffe: "*"
    sphinxext-opengraph: "*"
    ipython: "*"
    linkify-it-py: "*"
  pixi_pypi_dependencies:
    sphinx-pyscript: "*"

- name: myst-nb
  repo: executablebooks/MyST-NB
  doc_dir: docs
  html_pages_dir: _build/html
  doc_build_cmd: sphinx-build -T -E -b html ./ _build/html
  pixi_dependencies:
    sphinx: ">=8,<9"
    sphinx-book-theme: "*"
    myst-nb: "*"
    sphinx-copybutton: "*"
    sphinx-design: "*"
    sphinx-autodoc-typehints: "*"
    ipykernel: "*"
    jupytext: "*"
  pixi_pypi_dependencies:
    coconut: "*"
