- name: myst-parser
  repo: executablebooks/MyST-Parser
  doc_dir: docs
  html_pages_dir: _build/html
- name: myst-nb
  repo: executablebooks/MyST-NB
  doc_dir: docs
  html_pages_dir: _build/html
- name: jupyterhub
  repo: jupyterhub/jupyterhub
  doc_dir: docs
  html_pages_dir: build/html
  doc_build_cmd: sphinx-build -j auto -T -E -b html ./source build/html
- name: binder
  repo: jupyterhub/binder
  doc_dir: doc
  html_pages_dir: _build/html
  install: false
- name: repo2docker
  repo: jupyter/repo2docker
  doc_dir: docs
  html_pages_dir: build/html
- name: binderhub
  repo: jupyterhub/binderhub
  doc_dir: doc
  html_pages_dir: _build/html
  doc_build_cmd: sphinx-build -j auto -T -E -b html ./ _build/html
- name: ipywidgets
  repo: jupyter-widgets/ipywidgets
  doc_dir: docs
  html_pages_dir: build/html
  doc_build_cmd: sphinx-build -b html -D nbsphinx_allow_errors=True ./source build/html
- name: panel
  repo: holoviz/panel
  doc_dir: .
  html_pages_dir: .
  install: false
  doc_build_cmd: 'git checkout gh-pages'
  generator: html2dash
- name: hvplot
  repo: holoviz/hvplot
  doc_dir: .
  html_pages_dir: .
  install: false
  doc_build_cmd: 'git checkout gh-pages'
  generator: html2dash
- name: lumen
  repo: holoviz/lumen
  doc_dir: docs
  html_pages_dir: _build/html

- name: singularityadmin
  repo: hpcng/singularity-admindocs
  doc_dir: .
  html_pages_dir: _build/html
  install: false
- name: singularity
  repo: hpcng/singularity-userdocs
  doc_dir: .
  html_pages_dir: _build/html
  install: false
  doc_build_cmd: make html SKIPCLI=1
# - name: spack
#   repo: spack/spack
#   doc_dir: lib/spack/docs
#   html_pages_dir: _build/html
