name: dash-docs
channels:
  - conda-forge
dependencies:
  - alembic
  - basemap
  - bottleneck
  - bqplot
  - breathe
  - cartopy
  - cfgrib
  - cftime
  - climpred
  - dask
  - dask-jobqueue
  - dask-kubernetes
  - dask-sphinx-theme
  - distributed
  - doc2dash
  - docker-py
  - docrep
  - doxygen
  - escapism
  - fastapi
  - fsspec
  - h5netcdf
  - heapdict
  - intake
  - ipyleaflet
  - ipywidgets
  - iris
  - jax
  - jaxlib
  - jupyter-repo2docker
  - jupyter_telemetry
  - jupyterhub
  - jupyterlab
  - make
  - matplotlib>3
  - mkdocs
  - mkdocs-material
  - msgpack-python
  - nbsphinx
  - netcdf4
  - nodejs
  - numba
  - numpydoc
  - paramiko
  - pip
  - proplot
  - pydata-sphinx-theme
  - python=3.7
  - pytorch
  - rasterio
  - recommonmark
  - scipy
  - seaborn
  - sparse
  - sphinx-automodapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-gallery
  - sphinx-issues
  - sphinx_bootstrap_theme
  - sphinx_rtd_theme
  - tqdm
  - trio
  - xarray
  - xgcm
  - xtensor
  - zarr
  - zfpy
  - pip:
      - autodoc-traits
      - m2r
      - markdown-include
      - mkautodoc
      - pip
      - sphinx-fortran
      - sphinx-jsonschema
      - sphinx-pangeo-theme
      - sphinx_autodoc_typehints
      - sphinxcontrib-autoprogram
      - sphinxcontrib-napoleon
      - sphinxcontrib-trio
