name: dash-docs
channels:
  - conda-forge
dependencies:
  - alembic
  - basemap
  - bottleneck
  - bqplot
  - breathe
  - cartopy
  - cfgrib
  - cftime
  - climpred
  - coconut
  - dask-jobqueue
  - dask-kubernetes
  - dask-sphinx-theme
  - dask>=2.17
  - distributed
  - doc2dash
  - docker-py
  - docrep
  - doxygen
  - escapism
  - fastapi
  - fsspec
  - h5netcdf
  - heapdict
  - intake>=0.6.0
  - invoke
  - ipyleaflet
  - ipywidgets
  - iris
  - jax>=0.2.0
  - jaxlib>=0.1.55
  - jupyter-repo2docker
  - jupyter_telemetry
  - jupyterhub
  - jupyterlab
  - jupytext
  - make
  - matplotlib>3
  - mkdocs
  - mkdocs-material
  - msgpack-python
  - myst-parser
  - nbsphinx
  - netcdf4
  - nodejs
  - numba>=0.51
  - numpydoc
  - panel
  - paramiko
  - pip
  - proplot
  - pyarrow
  - pydata-sphinx-theme
  - pygit2
  - pytablewriter
  - python=3.7
  - pytorch
  - rasterio
  - recommonmark
  - scipy
  - seaborn
  - sparse
  - sphinx-automodapi
  - sphinx-click
  - sphinx-copybutton
  - sphinx-gallery
  - sphinx-issues
  - sphinx>2.4.4
  - sphinx_bootstrap_theme
  - sphinx_rtd_theme
  - tabulate
  - tqdm
  - trio
  - typer
  - xarray>=0.16
  - xgcm>=0.5.1
  - xrft
  - xtensor
  - zarr
  - zfpy
  - pip:
      - alabaster-jupyterhub
      - autodoc-traits
      - jupyter-telemetry
      - m2r
      - markdown-include
      - mkautodoc
      - myst-nb
      - scanpydoc
      - sphinx-autosummary-accessors
      - sphinx-book-theme
      - sphinx-fortran
      - sphinx-jsonschema
      - sphinx-panels
      - sphinx-pangeo-theme
      - sphinx-tabs
      - sphinx_autodoc_typehints
      - sphinxcontrib-apidoc
      - sphinxcontrib-autoprogram
      - sphinxcontrib-bibtex
      - sphinxcontrib-napoleon
      - sphinxcontrib-srclinks
      - sphinxcontrib-trio
      - sphinxext-rediraffe
