name: dash-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - alembic
  - attrs
  - Authlib
  - basemap
  - bottleneck
  - bqplot
  - breathe
  - cartopy>=0.18.0
  - cf-units
  - cfgrib
  - cftime
  - climpred
  - coconut
  - cython
  - dask-jobqueue
  - dask-kubernetes
  - dask-sphinx-theme
  - dask>=2.20
  - dill>=0.3.3
  - distributed>=2.20
  - django
  - doc2dash
  - docker-py
  - docrep
  - doxygen
  - emcee
  - escapism
  - fastapi>=0.61.2
  - flask
  - fsspec
  - geoviews
  - h5netcdf
  - heapdict
  - holoviews
  - httpx
  - intake>=0.6.0
  - invoke
  - ipyleaflet
  - ipywidgets
  - iris-sample-data
  - iris>=2.4.0
  - jax>=0.2.0
  - jaxlib>=0.1.55
  - jupyter_telemetry
  - jupyter-repo2docker
  - jupyterhub>=1.2.1
  - jupyterlab>=3
  - jupytext
  - m2r
  - make
  - markdown-include
  - matplotlib>3
  - mkdocs
  - mkdocs-material
  - msgpack-python
  - myst-nb
  - myst-parser
  - nbsphinx
  - netcdf4
  - networkx
  - nodejs
  - numba>=0.51
  - numpydoc
  - numpyro>=0.4.1
  - orjson
  - owslib
  - panel>=0.10.2
  - param
  - paramiko
  - pint
  - pip
  - plotly
  - proplot
  - pyarrow
  - pydantic>=1.8
  - pydata-sphinx-theme
  - pygit2
  - pyparsing
  - pyproj
  - pytablewriter
  - python=3.8
  - pytorch
  - rasterio
  - recommonmark
  - regionmask>=0.6.1
  - rich>= 9.9.0
  - scipy>=1.5.3
  - seaborn
  - sparse
  - sqlalchemy<1.4
  - starlette
  - tabulate
  - tqdm
  - trio>=0.17.0
  - typer
  - ujson
  - uvicorn
  - wrapt
  - xarray>=0.16.2
  - xesmf
  - xgcm>=0.5.1
  - xrft
  - xtensor
  - zarr>=2.5.0
  - zfpy
  # - dask-gateway
  # - dask-gateway-server-local
  - pip:
      - alabaster-jupyterhub
      - ansi2html
      - autodoc-traits
      - cPyparsing<2.4.6,>=2.4.5.0.1.2
      - flake8
      - flake8-quotes
      - funsor>=0.3.0
      - furo
      - linkify-it-py
      - lumen
      - manimgl
      - markdown-include
      - mdx_truly_sane_lists
      - mkautodoc
      - mkdocs-exclude
      - mkdocs-markdownextradata-plugin
      - mkdocs-material-extensions
      - releases
      - sphinx_autodoc_typehints
      - sphinx_bootstrap_theme
      - sphinx_markdown_tables
      - sphinx_material
      - sphinx_rtd_theme
      - sphinx_typlog_theme
      - sphinx-automodapi
      - sphinx-autosummary-accessors
      - sphinx-book-theme
      - sphinx-click
      - sphinx-copybutton
      - sphinx-fortran
      - sphinx-gallery>=0.8.1
      - sphinx-holoviz-theme
      - sphinx-issues
      - sphinx-js
      - sphinx-jsonschema
      - sphinx-notfound-page
      - sphinx-panels
      - sphinx-pangeo-theme
      - sphinx-tabs
      - sphinx>2.4.4
      - sphinxcontrib-apidoc
      - sphinxcontrib-autoprogram
      - sphinxcontrib-bibtex<2.0.0
      - sphinxcontrib-napoleon
      - sphinxcontrib-srclinks
      - sphinxcontrib-trio
      - sphinxext-opengraph
      - sphinxext-rediraffe
      - tensorflow_probability
      - zope.interface
