name: dash-docs
channels:
  - conda-forge
  - pyviz
dependencies:
  - alembic
  - arviz
  - basemap
  - bottleneck
  - bqplot
  - breathe
  - cartopy>=0.18.0
  - cf-units
  - cfgrib
  - cftime
  - climpred
  - coconut
  - cython
  - dask-jobqueue
  - dask-kubernetes
  - dask-sphinx-theme
  - dask>=2.20
  - dill>=0.3.3
  - distributed>=2.20
  - doc2dash
  - docker-py
  - docrep
  - doxygen
  - emcee
  - escapism
  - fastapi>=0.61.2
  - firefox
  - fsspec
  - geckodriver
  - geoviews
  - h5netcdf
  - heapdict
  - holoviews
  - intake>=0.6.0
  - invoke
  - ipyleaflet
  - ipywidgets
  - iris-sample-data
  - iris>=2.4.0
  - jax>=0.2.0
  - jaxlib>=0.1.55
  - jupyter-repo2docker
  - jupyter_telemetry
  - jupyter_telemetry
  - jupyterhub>=1.2.1
  - jupyterlab>=2.2.9
  - jupytext
  - m2r
  - make
  - markdown-include
  - matplotlib>3
  - mkdocs
  - mkdocs-material
  - msgpack-python
  - myst-nb
  - myst-parser
  - nbsite
  - nbsphinx
  - netcdf4
  - networkx
  - nodejs
  - numba>=0.51
  - numpydoc
  - numpyro>=0.4.1
  - owslib
  - panel>=0.10.2
  - param
  - paramiko
  - pip
  - proplot
  - pyarrow
  - pydata-sphinx-theme
  - pygit2
  - pymc3>=3.9.3
  - pyparsing==2.2.0
  - pytablewriter
  - python=3.7
  - pytorch
  - rasterio
  - recommonmark
  - scipy>=1.5.3
  - seaborn
  - selenium
  - sparse
  - sphinx-automodapi
  - sphinx-autosummary-accessors
  - sphinx-book-theme
  - sphinx-click
  - sphinx-copybutton
  - sphinx-gallery>=0.8.1
  - sphinx-issues
  - sphinx-panels
  - sphinx-tabs
  - sphinx>2.4.4
  - sphinx_bootstrap_theme
  - sphinx_rtd_theme
  - sphinxcontrib-apidoc
  - sphinxcontrib-autoprogram
  - sphinxcontrib-bibtex
  - sphinxcontrib-napoleon
  - tabulate
  - theano-pymc>=1.0.11
  - tqdm
  - trio>=0.17.0
  - typer
  - xarray>=0.16
  - xgcm>=0.5.1
  - xrft
  - xtensor
  - zarr>=2.5.0
  - zfpy
  - pip:
      - alabaster-jupyterhub
      - autodoc-traits
      - funsor>=0.3.0
      - mkautodoc
      - mkdocs-markdownextradata-plugin
      - mkdocs-material-extensions
      - releases
      - scanpydoc
      - sphinx-fortran
      - sphinx-holoviz-theme
      - sphinx-jsonschema
      - sphinx-notfound-page
      - sphinx-pangeo-theme
      - sphinx_autodoc_typehints
      - sphinxcontrib-srclinks
      - sphinxcontrib-trio
      - sphinxext-rediraffe
