name: CI
on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: dash-docsets-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: 3.7
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true
          add-pip-as-python-dependency: true
          activate-environment: dash-docs
          environment-file: ci/environment.yml
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          printenv | sort

      - shell: bash -l {0}
        env:
          SPHINXOPTS: "-j4"
          CONDA_PREFIX: "/usr/share/miniconda/condabin/conda"
          GO111MODULE: "on" # https://stackoverflow.com/questions/56475313/how-to-fix-go-get-warning-modules-disabled-by-go111module-auto-in-gopath-src
        run: |
          python build.py --config docsets.yaml

      - uses: actions/upload-artifact@v2
        with:
          name: docsets
          path: docsets

      - uses: actions/upload-artifact@v2
        with:
          name: feeds
          path: feeds

  deploy:
    name: dash-docsets-deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: docsets
      - uses: actions/download-artifact@v2
        with:
          path: /tmp/workspace

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: /tmp/workspace

      - name: Update Docsets + Feeds
        run: |
          cp -r ./images README.md ../
          rm -rf ./* .gitignore .isort.cfg .pre-commit-config.yaml ./.circleci
          mkdir -p ./docsets ./feeds
          cp -r /tmp/workspace/docsets/* ./docsets/
          cp -r /tmp/workspace/feeds/* ./feeds/
          cp -r ../images ../README.md ./
          ls -ltrh ./docsets
          ls -ltrh ./feeds
          git status
          git remote -v

      - name: Commit files
        run: |
          git config --global user.email "bot@andersonbanihirwe.dev"
          git config --global user.name "Samaritan"
          git add -A
          git commit -m "Automated deploy"
