name: CI
on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: dash-docsets-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: 3.7
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          add-pip-as-python-dependency: true
          activate-environment: dash-docs
          environment-file: ci/environment.yml
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          printenv | sort

      - shell: bash -l {0}
        env:
          SPHINXOPTS: "-j4"
          CONDA_PREFIX: "/opt/conda"
          GO111MODULE: "on" # https://stackoverflow.com/questions/56475313/how-to-fix-go-get-warning-modules-disabled-by-go111module-auto-in-gopath-src
        run: |
          python build.py --config docsets.yaml
