name: CI
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * 3,6' # “At 00:00 on Wednesday and Saturday"
  workflow_dispatch: # allows you to trigger manually

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: dash-docsets-build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      MKL_THREADING_LAYER: GNU
    strategy:
      fail-fast: true
      matrix:
        key: ['arctic', 'pacific', 'indian']
    timeout-minutes: 120
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@master
        with:
          # python-version: 3.8
          mamba-version: '*'
          channels: conda-forge,nodefaults
          channel-priority: strict
          auto-update-conda: false
          activate-environment: dash-docs
          environment-file: ci/environment.yml
          use-mamba: true
          miniforge-variant: Mambaforge

      - run: |
          conda info
          conda list
          # printenv | sort

      - run: |
          python builder.py build configs/${{ matrix.key }}.yaml

      - uses: actions/upload-artifact@v2
        with:
          name: docsets
          path: docsets
          retention-days: 3

      - uses: actions/upload-artifact@v2
        with:
          name: feeds
          path: feeds
          retention-days: 3

  deploy:
    name: dash-docsets-deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: /tmp/workspace/builds

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip typer beautifulsoup4 pyyaml requests rich pandas tabulate pydantic ruamel.yaml psutil
      - run: |
          python cli.py update-feed-list /tmp/workspace/builds/README.md --docset-dir /tmp/workspace/builds/docsets

      - name: Display structure of files to upload
        run: ls -R
        working-directory: /tmp/workspace/builds

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/workspace/builds
          user_name: 'GitHub Action'
          user_email: 'action@github.com'
          publish_branch: docsets
