name: CI
on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: dash-docsets-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: 3.7
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          add-pip-as-python-dependency: true
          activate-environment: dash-docs
          environment-file: ci/environment.yml
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          printenv | sort

      - shell: bash -l {0}
        env:
          SPHINXOPTS: "-j4"
          CONDA_PREFIX: "/usr/share/miniconda/condabin/conda"
          GO111MODULE: "on" # https://stackoverflow.com/questions/56475313/how-to-fix-go-get-warning-modules-disabled-by-go111module-auto-in-gopath-src
        run: |
          python build.py --config docsets.yaml

      - uses: actions/upload-artifact@v2
        with:
          name: dash docsets artifacts
          path: docsets

      - uses: actions/upload-artifact@v2
        with:
          name: dash docsets feeds
          path: feeds

  deploy:
    name: dash-docsets-deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          path: /tmp/workspace

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: /tmp/workspace
