name: CI
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * 3' # “At 00:00 on Wednesday."
  workflow_dispatch: # allows you to trigger manually

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: dash-docsets-build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      MKL_THREADING_LAYER: GNU
    strategy:
      fail-fast: true
      matrix:
        key:
          [
            'arctic',
            'atlantic',
            'indian',
            'pacific',
            'southern',
            'tahoe',
            'superior',
            'tanganyika',
          ]
    timeout-minutes: 60
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('ci/environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          mamba-version: '*'
          channels: 'conda-forge'
          channel-priority: strict
          add-pip-as-python-dependency: true
          activate-environment: dash-docs
          use-only-tar-bz2: true

      - run: |
          mamba env update -f ci/environment.yml
          conda info
          conda list
          printenv | sort

      - env:
          SPHINXOPTS: '-j4'
          CONDA_PREFIX: '/usr/share/miniconda/condabin/conda'
          GO111MODULE: 'on' # https://stackoverflow.com/questions/56475313/how-to-fix-go-get-warning-modules-disabled-by-go111module-auto-in-gopath-src
        run: |
          python cli.py build-from-config docsets.yaml --key ${{ matrix.key }}

      - uses: actions/upload-artifact@v2
        with:
          name: docsets
          path: docsets
          retention-days: 3

      - uses: actions/upload-artifact@v2
        with:
          name: feeds
          path: feeds
          retention-days: 3

  deploy:
    name: dash-docsets-deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: /tmp/workspace/builds

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          python -m pip install typer beautifulsoup4 pyyaml requests rich
      - run: |
          python cli.py update-feed-list /tmp/workspace/builds/README.md --docset-dir /tmp/workspace/builds/docsets

      - name: Display structure of files to upload
        run: ls -R
        working-directory: /tmp/workspace/builds

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/workspace/builds
          user_name: 'GitHub Action'
          user_email: 'action@github.com'
          publish_branch: docsets
